### PR TITLE
Added onPageLoad option to improve onKeyUp option

### PR DESCRIPTION
**Pull request by cjsheets**
Currently when onKeyUp is True, `that.loadAPI();` is called on each page load.

I believe this is unnecessary and the search would work best if loadAPI were called only when the field is focused. I added the onPageLoad option because I assume there are some who desire that behavior when onKeyUp is set.

I didn't re-minify the code to preserve the clarity of the request.

### CODE REVIEW

**Comment by cjsheets** [comment]
In a second commit, I added a check to set meta_description to an empty string if the API returns NULL (which Ghost allows if the description isn't set). 

Without this check the search function outputs the template tag `{{description}}` when the meta_description is NULL, which i don't think a user would expect.

It's up to you, though, if you think the check is needed.

**Comment by Windyo** [comment]
Hi there !
Thank you for taking the time to look into this and for the pull request :)
I think the check you added is a great addition.

Concerning the loadAPI part, I'll take some time tomorrow to see what to recommend in the Readme.md depending on the blog size. I think loading on focus could result in a performance degradation on bigger blogs, which should be documented.

Lastly before I merge tomorrow, could you push your changes to the minified files (and if I'm being very picky, change your space to a tab on line 27) ?

Thanks again ! 👍

**Comment by cjsheets** [comment]
Formatting is never too picky, glad you caught it. I went ahead and pushed the minified files and corrected the alignment.

I appreciate your building ghostHunter. It's very well put together and very useful. Let me know if there's anything else I should do.

**Comment by Windyo** [comment]
Thank you for your updates, and for the compliment ! @jamalneufeld is the one who did 90% of the code, I just do some adaptations when needed :)

I tested your version on blogs of varying sizes. Everything works, but I did find what I was expecting.
Starting at 100-ish posts, there is a noticeable lag (between 2 and 3 seconds) during which key entries may not be registered when using onKeyUp.
This should be written in the ReadMe in the section "###Preparing the search results with an API call on page-load", with a recommendation to use onPageLoad for bigger blogs.

Oh and remember to version bump to 0.3.2 and give yourself credit in the changelog if you want to.

(Also, when the filterfields branch goes live removing the "markdown" field from the query should be recommended for anyone wanting to use the onKeyUp function.) < Just noting this down for myself

Other than that we're all clear to merge !

**Pull request merged**
