### PR TITLE
Adding feature_image to the payload.

### PR DESCRIPTION
**Pull request by CleristonBernardes**
- Adding feature_image to the payload. This way the user can use a post image into template.

### CODE REVIEW

**Comment by Windyo** [comment]
I'm going to test this weekend after next, swamped before that.

The only issue I see this possibly having is for large blogs, depending on how the Ghost API handles the image calls.

I'll review and then merge if there's no performance downside - otherwise this may need to be paramaterized.

Thanks a lot for your pull request!

**Comment by CleristonBernardes** [comment]
I understand your point but what is being retrieved is the image url. If you are concerned when the page is rendered, the developer can avoid this value. Moreover I would say that a pagination parameter would be interesting.

**Comment by Windyo** [comment]
Thanks for the precisions. I just need to check the api docs again. I thought I remembered something about them wanting to serve a base64 when queried with a certain parameter.

Re: pagination it's actually already in there to some extent, I just hard-coded it to "all" as most standard search use is not date or page relative by default — and this was once one of ghosthunter's most reported issue.

Adding a way to pass date filters or pagination is nice, but ghost is supposed to deliver their App Api sometime in the future, which will make a major rewrite of ghostHunter necessary anyway.

All that to say I'll check the docs, test a bit, and probably approve your merge—in a week or so. Thanks again for your work!

Sent from BlueMail<http://www.bluemail.me/r?b=12095>

**Comment by Windyo** [comment]
Tested and no problem from my side.

**Pull request merged**
