### PR TITLE
Version 0.5.0 Levenstein updates and fuzzy matching

### PR DESCRIPTION
**Pull request by fbennett**
* Graceful Levenshtein updating of search list
* Search queries as fuzzy match to each term, joined by AND
* Force query words to lowercase
* Fix an issue with failure of DOM updates on first search
* Update README
* Update changelog.txt

### CODE REVIEW

**Comment by fbennett** [comment]
Hope this checks out okay in trials!

**Comment by Windyo** [comment]
I'll look at it this weekend, kinda swamped ATM.

Quick question: you changed from .4 to .5 - does that mean you're expecting breaking changes ?

Cheers

**Comment by fbennett** [comment]
No rush at all. The changes require an id and a specific class attribute on ``result_template`` for screen updates to work correctly. It's a small change for theme developers, but if they have defined their own ``result_template`` and don't make the adjustment, screen updates will not work correctly.

**Comment by fbennett** [comment]
I just force-pushed a further small change. Testing locally, we found that search could be broken if user made a search attempt immediately on first access to the site. Running ``indexing_start`` immediately when index generation is required helps protect against that glitch. No other impact.

**Comment by fbennett** [comment]
Fixed a couple of other bugs, including what looks like a change in the way dates are handled in some contexts---the tool worked on our production server with MySQL and Ghost v1.20.0, and failed locally on a v1.20.3 sqlite3 installation. A tweak to normalize the date form for an API call fixed it. Should be pretty solid at this point.

**Comment by Windyo** [comment]
You're fixing stuff too fast xD I'll look at it this weekend, thanks

Sent from BlueMail<http://www.bluemail.me/r?b=11745>
On Jan 25, 2018, at 16:09, Frank Bennett <notifications@github.com<mailto:notifications@github.com>> wrote:

Fixed a couple of other bugs, including what looks like a change in the way dates are handled in some contexts---the tool worked on our production server with MySQL and Ghost v1.20.0, and failed locally on a v1.20.3 sqlite3 installation. A tweak to normalize the date form for an API call fixed it. Should be pretty solid at this point.

**Comment by fbennett** [comment]
Yeah, it got to be a little obsessive there for a bit. Should be settled now, though. Have a good weekend!

**Comment by fbennett** [comment]
Rats. Searches are behaving weirdly on first-access with iOS devices. Erratically. Working on it, but not ready for merge yet. More soon ...

**Comment by fbennett** [comment]
There we go, the deed is done. We're now getting identical results without crashes on Linux and iOS devices. I've squashed everything into a single commit. I *think* this does it. :crossed_fingers:

**Comment by fbennett** [comment]
Added one more small tweak. The ``meta_description`` field does not (yet) return anything for posts. The user's hand-drafted description, if any, comes through in ``custom_excerpt``, so I shifted to that instead for the ``description`` value in the index return.

**Comment by Windyo** [comment]
@fbennett I ahven't forgotten you, I got a bit swamped, sorry. I'll finish testing and put it live by Sunday barring any issues.

**Comment by fbennett** [comment]
No worries at all. I know swamped.

**Comment by Windyo** [comment]
thanks :)

**Pull request merged**
